### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by KarolS**
First of all, I am really sorry that this pull request contains several disjointed features. If you wish, I can delete this PR and create one smaller pull request or several separate pull requests for each feature.

While experimenting with Ozmoo, I decided to scratch my own itch and add few features that I liked. Here are their descriptions:

* "Allow for custom boot file name" – the default file name "story" is fine, but I thought that adding the ability to customize it could be useful.

* "Use undocumented/illegal 6502 instructions" – I found several spots in the code that could be optimized with the so-called undocumented/illegal instructions. This obviously breaks SuperCPU compatibility, so I stubbed it out if illegals are enabled. The only two instructions I found a use for were LAX and SBX. It's not a huge optimization, but still it's kinda free.

* "Add command line switches for SLOW and NODARKMODE. Don't inform about the dark mode if it's absent" – I added command line flags, so I could test various builds easier, and noticed that the splash screen says "F1 for dark mode" even if the program is compiled with dark mode disabled.

* "Fail if there's exactly 0 free unbanked VMEM blocks for static data" – exactly what is says on the tin. If the whole unbanked RAM is taken by dynamic memory and the game contains non-dynamic memory, then fail. I tested how a build with 0 blocks works on C64 and the VM simply crashes, so I added a check for it. Maybe it would work fine C128 and I was too overcautious?

* "Detect unused opcodes and remove their implementations" – This is a huge memory saving, it can save few bytes, but in some cases it can save an entire kilobyte. It uses the txd decompiler (a part of ztools) to see which opcodes are used and which are not and then removes the implementations of the unused ones.

* "Add a very stripped character set" – if a game doesn't use underscores or other tricky symbols, then I added an option to remove the conversion lookup table for printing, so the interpreted is slightly smaller and it prints slightly faster.

With all those tweaks enabled, I managed to get "An Act of Murder" by Christopher Huang to work – it's slow as hell, even with a REU, but it fits, with exactly one block for non-dynamic memory. I haven't tested it without REU, but I think it would be literally unplayable then. The game has 37511 bytes of dynamic memory, Here's a compilation log:

```
D:\programy\ozmoo>ruby make.rb -v -sl -ru -il -fn:a -cm:zz -dd -u -D3 d:\programy\if\ActofMurder.z8
Reading file d:\programy\if\ActofMurder.z8...
D:\programy\ztools\txd.exe d:\programy\if\ActofMurder.z8
ADD, AND, BUFFER_MODE, CALL_1N, CALL_1S, CALL_2N, CALL_2S, CALL_VN, CALL_VN2, CALL_VS, CALL_VS2, CHECK_ARG_COUNT, CLEAR_ATTR, COPY_TABLE, DEC, DIV, ERASE_WINDOW, GET_CHILD, GET_PARENT, GET_PROP, GET_PROP_ADDR, GET_PROP_LEN, GET_SIBLING, INC, INPUT_STREAM, INSERT_OBJ, JE, JG, JIN, JL, JUMP, JZ, LOADB, LOADW, MOD, MUL, NEW_LINE, NOT, OR, OUTPUT_STREAM, PRINT, PRINT_ADDR, PRINT_CHAR, PRINT_NUM, PRINT_OBJ, PRINT_PADDR, PRINT_RET, PULL, PUSH, PUT_PROP, QUIT, RANDOM, READ, READ_CHAR, REMOVE_OBJ, RESTART, RESTORE, RESTORE_UNDO, RET, RET_POPPED, RFALSE, RTRUE, SAVE, SAVE_UNDO, SET_ATTR, SET_COLOUR, SET_CURSOR, SET_TEXT_STYLE, SET_WINDOW, SPLIT_WINDOW, STORE, STOREB, STOREW, SUB, TEST_ATTR, TOKENISE, VERIFY
Dynmem blocks: 74
$zmachine_memory_size = 385776
$story_size = 386048
D:\programy\acme0.97win\acme\acme.exe --setpc 2049 -DCACHE_PAGES=4 -DSTACK_PAGES=4 -DZ8=1 -DCONF_TRK=1 --cpu 6510 --format cbm -DNOSECTORPRELOAD=1 -DTARGET_C64=1 -DBORDERCOL=0 -DSLOW=1 -DILLEGAL=1 -DNODARKMODE=1 -DUNSAFE=1 -DMINIMUM_CHARS=1 -DVMEM=1 -DREMOVE_ART_SHIFT=1 -DREMOVE_CATCH=1 -DREMOVE_CHECK_UNICODE=1 -DREMOVE_DEC_CHK=1 -DREMOVE_ENCODE_TEXT=1 -DREMOVE_ERASE_LINE=1 -DREMOVE_GET_CURSOR=1 -DREMOVE_GET_NEXT_PROP=1 -DREMOVE_INC_CHK=1 -DREMOVE_LOAD=1 -DREMOVE_LOG_SHIFT=1 -DREMOVE_PRINT_TABLE=1 -DREMOVE_PRINT_UNICODE=1 -DREMOVE_SCAN_TABLE=1 -DREMOVE_SET_FONT=1 -DREMOVE_SOUND_EFFECT=1 -DREMOVE_TEST=1 -DREMOVE_THROW=1 -l "D:/programy/ozmoo/temp/acme_labels.txt" --outfile "D:/programy/ozmoo/temp/ozmoo" ozmoo.asm
Interpreter size: 10708 bytes.
Dynamic memory: 37888 bytes
VMEM blocks in RAM is 25
Unbanked VMEM blocks in RAM is 1
Max preload blocks adjusted to total vmem size, from 256 to 25.
Creating disk image...
Free disk blocks at start: 679
Creating disk image...
Free disk blocks at start: 681
Creating disk image...
Free disk blocks at start: 681
Free disk blocks on disk #1 after story data has been written: 679
Free disk blocks on disk #2 after story data has been written: 1
Free disk blocks on disk #3 after story data has been written: 1
Max file size is 168656 bytes.
D:\programy\exomizer\exomizer.exe sfx 2049 -B -M256 -C  "D:/programy/ozmoo/temp/ozmoo" "D:/programy/ozmoo/temp/compmem.tmp"@14848,0,50688 -o "D:/programy/ozmoo/temp/ozmoo_zip"
 Reading "D:/programy/ozmoo/temp/ozmoo", loading from $0801 to $3A00.
 Reading "D:/programy/ozmoo/temp/compmem.tmp", loading from $3A00 to $10000.
 Crunched data reduced 34760 bytes (54.75%)
 Writing "D:/programy/ozmoo/temp/ozmoo_zip" as prg, saving from $0801 to $7965.
D:\programy\GTK3VICE-3.5-win64\bin\c1541.exe -attach "c64_ActofMurder_boot.d64" -write "D:/programy/ozmoo/temp/ozmoo_zip_good" a
writing file `OZMOO_ZIP_GOOD' as `A' to unit 8
Successfully built game as c64_ActofMurder_boot.d64 + c64_ActofMurder_story_1.d64 + c64_ActofMurder_story_2.d64
```

### CODE REVIEW

**Comment by johanberntsson** [comment]
Thanks a lot, very impressive! Many interesting ideas here but having all as a big pull request makes it a bit hard to review properly. We will check and discuss and get back to you, but it may take some time.

**Comment by johanberntsson** [comment]
We have looked at your features and the code, and decided that we would like to merge:
- allow for custom boot name
- switches for SLOW and NODARKMODE
- VMEM block check

We will not merge your fixes for undocumented 6502 instructions, unused op-codes, and stripped character sets. We think that these features are interesting and impressive but we want Ozmoo to be complete standard-compliant interpreter working reliably on all applicable platforms, rather than something that is customized for each game. So these features are good but they don't fit with our project aims.

How would you like to proceed? If you resubmit the three features we are willing to merge, preferably as separate pull requests for each feature, then we will merge them. Another option is that we simply extract the diffs for these features from this pull request and patch them by hand, but then your contribution will be less visible in the commit history. In either case we will of course credit your contribution in the documentation.

Looking forward to hearing from you.

**Comment by KarolS** [comment]
I understand where you're coming from: undocumented instructions will cause a game that works on a stock C64 crash on SuperCPU or on Mega65, and the other two things are a little bit risky to use (mangled output or a crash with [Not implemented] two hours into the game is not something anyone would want).
I'll re-submit the other three as separate pull requests later today. And as for those more experimental changes, I'll keep them in my fork only.

**Comment by fredrikr** [comment]
FYI: I saw a report of LAX not being reliable on all C64 models either: http://www.oxyron.de/html/opcodes02.html

**Comment by KarolS** [comment]
That's only LAX with an immediate, which I never use. Other addressing modes are stable.

**Pull request closed without merging**
