### PR TITLE
Add support to Italian language

### PR DESCRIPTION
**Pull request by gpz500**
Hello!
I propose some changes to support the Italian language.
I've added the `-cm:it` option to `make.rb` and the corresponding case in `asm/streams.asm` (selected a set of 12 graphical characters for the accented ones). I also added three character maps: the first derived from `PXLfont-rf.fnt`, the second derived from `clairsys.fnt`, and the last derived from the original Commodore 64 ROM's character map.
I have some strong doubt about copyrights and licences... I don't know if I could derive my work from the original character map and/or other contributors work. I even don't know if my `.license.txt` files are right or acceptable. Waiting some follow up from you!
Best regards,
Alessandro

### CODE REVIEW

**Comment by fredrikr** [comment]
Looks like good changes, and we are very happy to see your interest in Ozmoo and the work you put in. A few comments:

The italian characters have been mapped to $a1-$ac. This will make it really hard for the player to figure out and remember how to type these characters. Wouldn't it make more sense to map say e-grave to CTRL-E and e-acute to CBM-E etc?

Also, about the fonts: I believe one of the fonts have a license which permits derivative works, and the other doesn't. How about we send the font files you have produced to the people who produced the fonts and ask if they want to make any adjustments, and let them keep control of the italian versions of the fonts as well?

As for the Commodore font: The Mega 65 project (and some others, I'm sure) have concluded that an 8-bit font can't really be protected because there are only so many ways to make the letter A as an 8x8 pixel monochrome image. We haven't really decided to follow their lead on this though. We'll need to get back to you on this issue.

**Comment by gpz500** [comment]
> The italian characters have been mapped to $a1-$ac. This will make it really hard for the player to figure out and remember how to type these characters. Wouldn't it make more sense to map say e-grave to CTRL-E and e-acute to CBM-E etc?

I've catched the point. In the second commit (70a1123e9ecbc56296a801daf642f61a84a4bb6e) I've revised the character maps in the following way: precedence to the lowercase letters à,è,é,ì,ò,ù by, respectively, typing CBM-{a,e,r,i,o,u}. The uppercase letters (À,È,É,Ì,Ò,Ù) are obtained typing, respectively, CBM-{z,d,f,k,l,j}, that are the keys just under the base ones. Less simple to figure out and remember, but consider that:

1. I presume I have to limit the redefinitions to the printable subset of PETSCII set, and not all the CTRL- combinations produce printable chars, while all the chosen CBM- combinations are printable
2. even in the PC and Mac Italian keyboard layouts there are only the lowercase accented letters (see https://it.wikipedia.org/wiki/File:Italian_Keyboard_layout.svg; very oddly, in Italian doesn't exist any ç letter, even if every Italian keyboard in the world has that... :flushed:); for the uppercase ones you have to use tricks and/or special keys sequences (eg: to produce À you have to type ALT+0192 on the numeric pad on Windows, and OPTION+SHIFT+W on a Mac). So, it's perfectly acceptable having less comfortable combinations for the uppercase letters. 

> Also, about the fonts: I believe one of the fonts have a license which permits derivative works, and the other doesn't. How about we send the font files you have produced to the people who produced the fonts and ask if they want to make any adjustments, and let them keep control of the italian versions of the fonts as well?

I fully agree! Just get the files from my last commit.
 
> As for the Commodore font: The Mega 65 project (and some others, I'm sure) have concluded that an 8-bit font can't really be protected because there are only so many ways to make the letter A as an 8x8 pixel monochrome image. We haven't really decided to follow their lead on this though. We'll need to get back to you on this issue.

As you prefer :stuck_out_tongue_winking_eye:, just let me know if I have to remove the charmap derived from Commodore font.

**Comment by fredrikr** [comment]
Oh, you are right about CTRL-combinations not being useful of course - my bad. I think the new mappings make sense.

And you are right about how typing capital versions of the characters is a lot less important, especially since the interpreter should automatically convert all input to lowercase before storing it in Z-machine memory, meaning that the game has no way of telling if you typed È or è - it will just look like è to the game in either case.

Have you tried playing a game in Italian using these mappings and fonts? Have you checked that the downcasing works properly for all characters (i.e. the game should recognize CAFFÈ as the same word as caffè)?

I will ask the font creators to have a look at the fonts.

**Comment by gpz500** [comment]
> Have you tried playing a game in Italian using these mappings and fonts? Have you checked that the downcasing works properly for all characters (i.e. the game should recognize CAFFÈ as the same word as caffè)?

It didn't work at beginning. Then I've seen in file `asm/text.asm`, in the procedure `translate_petscii_to_zscii`, that characters with a defined translation skip the conversion to lowercase. So (commit b5d8568a9c21cf82d6b38fc23f7fca9741891d3a) I've put the conversion to lowercase straight into the `character_translation_table_in` of `asm/streams.asm`. Now it works properly, eg: the direction 'GIÙ' (down in Italian) works the same as 'giù'.

**Comment by fredrikr** [comment]
Ah, right you are. Since all characters which aren't part of 7-bit ASCII need to be in the character mapping table anyway, it made more sense to downcase it right away in the table - it's both faster and uses less memory than downcasing them in code. It's still shown as uppercase when typed in player input, but it's stored as lowercase in the Z-machine. Your latest changes look fine.

Both of the font creators are happy to let us distribute Italian versions of the fonts. However, both of them feel that the uppercase letters need to be reworked, and they intend to do this themselves. I believe they will make these letters lower to make room for the accent above the letter.

We have decided to include altered system fonts as well. However, I think you need to make the uppercase letters two pixels lower and place the accent above the character. This probably means Ò and ò will be indistinguishable, but that's okay. I'm guessing Ò isn't used much anyway?

**Comment by fredrikr** [comment]
Please note: Don't make AEIOU lower, just ÀÈÌÒÙ.

**Comment by fredrikr** [comment]
image

This is what I meant. What do you think?

**Comment by gpz500** [comment]
system-it
I would prefer this one. Please note that the À is different.

So, if you agree, I'll do a commit with:

1. this system-it.fnt
1. the other fonts removed 

About the Ò, actually there are a lot (almost every) future tenses that have it: avrò (I will have), amerò (I will love), mangerò (I will eat), sarò (I will be), etc. etc. etc. ;-). Anyway, I presume that they are rarely used in IF, especially in uppercase. So, having ò and Ò equal is okay.

**Comment by fredrikr** [comment]
Agreed. Your change to À is an improvement. Please commit this and remove the other fonts.

I have now received an italian version of PXLfont-rf by Retrofan. Will add it after merging this.

**Comment by gpz500** [comment]
I've just committed last modifications... ready to be merged!

**Comment by fredrikr** [comment]
All that we've talked about looks good, but I just realized something else:

Have you tried inputing characters like È and À, and they worked like è and
à? PETSCII codes $a0-$bf are supposed to just be shadows of $c0-$df,
meaning that outputing $a0-$bf give the same results as outputing $c0-$df,
but when reading input from the keyboard the kernal should never return any
of the codes $a0-$bf. If you could type À and it was considered the same as
à, there is something fishy going on.

Regarding the license for the system font. Since we didn't create the base
font, I don't think you (or I) should claim copyright for the font, or
require others to ask you before using it. I suggest a license text like:


system-it.fnt: Ozmoo version, for Italian language, of the original
Commodore 64 system font

License:

This font is a version of the Commodore 64 system font, modified to include
Italian accented characters. It may be freely used with the Z-code
interpreter Ozmoo, including embedding the font in games built with Ozmoo.
We do not own the copyright for this font. The base font is available in
every Commodore 64 anyway, and the modifications (the accented characters)
are provided for free.



/Fredrik

**Comment by gpz500** [comment]
>PETSCII codes $a0-$bf are supposed to just be shadows of $c0-$df,
meaning that outputing $a0-$bf give the same results as outputing $c0-$df,
but when reading input from the keyboard the kernal should never return any
of the codes $a0-$bf.

In my opinion, this is not correct. In http://sta.c64.org/cbm64petkey.html you can see the table and read the Note 2 that says:
"Codes $60-$7F and $E0-$FE are not used. Although you can print them, these are, actually, copies of codes $C0-$DF and $A0-$BE."
So codes $A0-$BF aren't the shadow of $C0-$DF. Rather $E0-$FE are the shadow of $A0-$BE.
You can also see the column with the key combinations: the kernal never returns the codes $60-$7F and $E0-$FF when reading the keyboard input. Instead, it returns $A0-BF _AND_ $C0-$DF, without any overlapping.

>If you could type À and it was considered the same as à, there is something fishy going on.

This is the same as when you type "A" and this is considered the same as "a", doesn't it? Anyway, all the cases I tried work as expected.

For the license, I completely agree and I've modified the license file as you suggested.

**Comment by fredrikr** [comment]
Okay, could be that I'm just confused. If it works, all is fine.

Let's merge it.

**Pull request merged**
